version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
